/**
 * Países y códigos especiales de la MRZ (cambio otros-documentos, OD-04; design.md decisión 2).
 *
 * Códigos: ISO 3166-1 alfa-3 (249) y los especiales de ICAO 9303 parte 3, más `UTO` (Utopía, espécimen de ICAO).
 * Los códigos no tienen restricción de licencia; los nombres en español se redactan en este repositorio (MIT).
 */

/** Código de país de la MRZ (sin relleno) -> nombre en español. */
export const PAISES_ICAO: Readonly<Record<string, string>> = Object.freeze({
  AFG: "Afganistán",
  ALA: "Islas Åland",
  ALB: "Albania",
  DZA: "Argelia",
  ASM: "Samoa Americana",
  AND: "Andorra",
  AGO: "Angola",
  AIA: "Anguila",
  ATA: "Antártida",
  ATG: "Antigua y Barbuda",
  ARG: "Argentina",
  ARM: "Armenia",
  ABW: "Aruba",
  AUS: "Australia",
  AUT: "Austria",
  AZE: "Azerbaiyán",
  BHS: "Bahamas",
  BHR: "Baréin",
  BGD: "Bangladés",
  BRB: "Barbados",
  BLR: "Bielorrusia",
  BEL: "Bélgica",
  BLZ: "Belice",
  BEN: "Benín",
  BMU: "Bermudas",
  BTN: "Bután",
  BOL: "Bolivia",
  BES: "Bonaire, San Eustaquio y Saba",
  BIH: "Bosnia y Herzegovina",
  BWA: "Botsuana",
  BVT: "Isla Bouvet",
  BRA: "Brasil",
  IOT: "Territorio Británico del Océano Índico",
  BRN: "Brunéi",
  BGR: "Bulgaria",
  BFA: "Burkina Faso",
  BDI: "Burundi",
  CPV: "Cabo Verde",
  KHM: "Camboya",
  CMR: "Camerún",
  CAN: "Canadá",
  CYM: "Islas Caimán",
  CAF: "República Centroafricana",
  TCD: "Chad",
  CHL: "Chile",
  CHN: "China",
  CXR: "Isla de Navidad",
  CCK: "Islas Cocos",
  COL: "Colombia",
  COM: "Comoras",
  COG: "Congo",
  COD: "República Democrática del Congo",
  COK: "Islas Cook",
  CRI: "Costa Rica",
  CIV: "Costa de Marfil",
  HRV: "Croacia",
  CUB: "Cuba",
  CUW: "Curazao",
  CYP: "Chipre",
  CZE: "Chequia",
  DNK: "Dinamarca",
  DJI: "Yibuti",
  DMA: "Dominica",
  DOM: "República Dominicana",
  ECU: "Ecuador",
  EGY: "Egipto",
  SLV: "El Salvador",
  GNQ: "Guinea Ecuatorial",
  ERI: "Eritrea",
  EST: "Estonia",
  SWZ: "Esuatini",
  ETH: "Etiopía",
  FLK: "Islas Malvinas",
  FRO: "Islas Feroe",
  FJI: "Fiyi",
  FIN: "Finlandia",
  FRA: "Francia",
  GUF: "Guayana Francesa",
  PYF: "Polinesia Francesa",
  ATF: "Territorios Australes Franceses",
  GAB: "Gabón",
  GMB: "Gambia",
  GEO: "Georgia",
  DEU: "Alemania",
  GHA: "Ghana",
  GIB: "Gibraltar",
  GRC: "Grecia",
  GRL: "Groenlandia",
  GRD: "Granada",
  GLP: "Guadalupe",
  GUM: "Guam",
  GTM: "Guatemala",
  GGY: "Guernsey",
  GIN: "Guinea",
  GNB: "Guinea-Bisáu",
  GUY: "Guyana",
  HTI: "Haití",
  HMD: "Islas Heard y McDonald",
  VAT: "Santa Sede",
  HND: "Honduras",
  HKG: "Hong Kong",
  HUN: "Hungría",
  ISL: "Islandia",
  IND: "India",
  IDN: "Indonesia",
  IRN: "Irán",
  IRQ: "Irak",
  IRL: "Irlanda",
  IMN: "Isla de Man",
  ISR: "Israel",
  ITA: "Italia",
  JAM: "Jamaica",
  JPN: "Japón",
  JEY: "Jersey",
  JOR: "Jordania",
  KAZ: "Kazajistán",
  KEN: "Kenia",
  KIR: "Kiribati",
  PRK: "Corea del Norte",
  KOR: "Corea del Sur",
  KWT: "Kuwait",
  KGZ: "Kirguistán",
  LAO: "Laos",
  LVA: "Letonia",
  LBN: "Líbano",
  LSO: "Lesoto",
  LBR: "Liberia",
  LBY: "Libia",
  LIE: "Liechtenstein",
  LTU: "Lituania",
  LUX: "Luxemburgo",
  MAC: "Macao",
  MDG: "Madagascar",
  MWI: "Malaui",
  MYS: "Malasia",
  MDV: "Maldivas",
  MLI: "Malí",
  MLT: "Malta",
  MHL: "Islas Marshall",
  MTQ: "Martinica",
  MRT: "Mauritania",
  MUS: "Mauricio",
  MYT: "Mayotte",
  MEX: "México",
  FSM: "Micronesia",
  MDA: "Moldavia",
  MCO: "Mónaco",
  MNG: "Mongolia",
  MNE: "Montenegro",
  MSR: "Montserrat",
  MAR: "Marruecos",
  MOZ: "Mozambique",
  MMR: "Myanmar",
  NAM: "Namibia",
  NRU: "Nauru",
  NPL: "Nepal",
  NLD: "Países Bajos",
  NCL: "Nueva Caledonia",
  NZL: "Nueva Zelanda",
  NIC: "Nicaragua",
  NER: "Níger",
  NGA: "Nigeria",
  NIU: "Niue",
  NFK: "Isla Norfolk",
  MKD: "Macedonia del Norte",
  MNP: "Islas Marianas del Norte",
  NOR: "Noruega",
  OMN: "Omán",
  PAK: "Pakistán",
  PLW: "Palaos",
  PSE: "Palestina",
  PAN: "Panamá",
  PNG: "Papúa Nueva Guinea",
  PRY: "Paraguay",
  PER: "Perú",
  PHL: "Filipinas",
  PCN: "Islas Pitcairn",
  POL: "Polonia",
  PRT: "Portugal",
  PRI: "Puerto Rico",
  QAT: "Catar",
  REU: "Reunión",
  ROU: "Rumania",
  RUS: "Rusia",
  RWA: "Ruanda",
  BLM: "San Bartolomé",
  SHN: "Santa Elena, Ascensión y Tristán de Acuña",
  KNA: "San Cristóbal y Nieves",
  LCA: "Santa Lucía",
  MAF: "San Martín (parte francesa)",
  SPM: "San Pedro y Miquelón",
  VCT: "San Vicente y las Granadinas",
  WSM: "Samoa",
  SMR: "San Marino",
  STP: "Santo Tomé y Príncipe",
  SAU: "Arabia Saudita",
  SEN: "Senegal",
  SRB: "Serbia",
  SYC: "Seychelles",
  SLE: "Sierra Leona",
  SGP: "Singapur",
  SXM: "San Martín (parte neerlandesa)",
  SVK: "Eslovaquia",
  SVN: "Eslovenia",
  SLB: "Islas Salomón",
  SOM: "Somalia",
  ZAF: "Sudáfrica",
  SGS: "Islas Georgias del Sur y Sandwich del Sur",
  SSD: "Sudán del Sur",
  ESP: "España",
  LKA: "Sri Lanka",
  SDN: "Sudán",
  SUR: "Surinam",
  SJM: "Svalbard y Jan Mayen",
  SWE: "Suecia",
  CHE: "Suiza",
  SYR: "Siria",
  TWN: "Taiwán",
  TJK: "Tayikistán",
  TZA: "Tanzania",
  THA: "Tailandia",
  TLS: "Timor Oriental",
  TGO: "Togo",
  TKL: "Tokelau",
  TON: "Tonga",
  TTO: "Trinidad y Tobago",
  TUN: "Túnez",
  TUR: "Turquía",
  TKM: "Turkmenistán",
  TCA: "Islas Turcas y Caicos",
  TUV: "Tuvalu",
  UGA: "Uganda",
  UKR: "Ucrania",
  ARE: "Emiratos Árabes Unidos",
  GBR: "Reino Unido",
  USA: "Estados Unidos",
  UMI: "Islas Ultramarinas Menores de Estados Unidos",
  URY: "Uruguay",
  UZB: "Uzbekistán",
  VUT: "Vanuatu",
  VEN: "Venezuela",
  VNM: "Vietnam",
  VGB: "Islas Vírgenes Británicas",
  VIR: "Islas Vírgenes de los Estados Unidos",
  WLF: "Wallis y Futuna",
  ESH: "Sahara Occidental",
  YEM: "Yemen",
  ZMB: "Zambia",
  ZWE: "Zimbabue",
  // Códigos especiales de ICAO 9303 parte 3.
  D: "Alemania",
  GBD: "Reino Unido (ciudadano de territorio británico de ultramar)",
  GBN: "Reino Unido (nacional británico de ultramar)",
  GBO: "Reino Unido (ciudadano británico de ultramar)",
  GBP: "Reino Unido (persona protegida británica)",
  GBS: "Reino Unido (súbdito británico)",
  UNA: "Agencia especializada de las Naciones Unidas",
  UNK: "Kosovo (Misión de las Naciones Unidas)",
  UNO: "Naciones Unidas",
  XOM: "Soberana Orden de Malta",
  XXA: "Apátrida",
  XXB: "Refugiado (Convención de 1951)",
  XXC: "Refugiado (otro)",
  XXX: "Nacionalidad no especificada",
  EUE: "Unión Europea",
  RKS: "Kosovo",
  // Espécimen de ICAO 9303: no es un país real.
  UTO: "Utopía (espécimen ICAO)",
});

const CODIGO_ESPECIMEN = "UTO";

/** Resultado de `buscarPaisIcao`. */
export interface PaisIcao {
  /** Código sin el relleno `<` (p. ej. `D<<` -> `D`). */
  codigo: string;
  nombre: string | null;
  /** `"pais-desconocido"` si no está en la tabla; `"pais-especimen"` para `UTO`. */
  warnings: string[];
}

/** Busca un campo de país de la MRZ (3 caracteres con relleno) en `PAISES_ICAO` (OD-04). */
export function buscarPaisIcao(campo: string): PaisIcao {
  const codigo = campo.replace(/<+$/, "");
  const nombre = Object.hasOwn(PAISES_ICAO, codigo) ? (PAISES_ICAO[codigo] as string) : null;
  if (nombre === null) return { codigo, nombre, warnings: ["pais-desconocido"] };
  return { codigo, nombre, warnings: codigo === CODIGO_ESPECIMEN ? ["pais-especimen"] : [] };
}
